### ISSUE TITLE
Add option to disable "STOP" button

### ISSUE THREAD

**Issue by Kupie** [alextd/RimWorld-EnhancementPack#17]
Hello!

I love the Enhancement pack! I can't go without it, even when playing Multiplayer with friends so that leads to a request:

Would it be possible to have an option to disable the "STOP" command? In Multiplayer, it's one of the few buttons that can't be removed/disabled but still causes desyncs. An option to not have it would be nice as we can just draft/undraft as a workaround, but people may still hit "STOP" by accident.

**Comment by alextd** [comment]
Ayyyy I went back in time and made this happen:

![image](https://user-images.githubusercontent.com/101399/191369052-8d0fa5fd-b27f-4179-a205-45ad81b3752c.png)

**Comment by Kupie** [comment]
Oh good lord I'm a fucking idiot

Thank you so much for your mod, it's up there in the top 5 QoL mods I'd love for Rimworld to have implemented in the base game. Sorry for wasting your time and hope you have a great week!
