### ISSUE TITLE
Performance request: Harmony patches on Verse.TickList:Tick

### ISSUE THREAD

**Issue by arademacker** [alextd/RimWorld-EnhancementPack#21]
I was recently hunting down performance issues in my game, as since Anomaly it has just been crawling, even with a tiny mod list.

While debugging I noticed TD Enhancement Pack adds two Harmony patches to core Verse functions:
```
TD_Enhancement_Pack.TickGrow
TD_Enhancement_Pack.TickGrow_Harvest
```
from [Overlays/TreeGrowthOverlay.cs](https://github.com/alextd/RimWorld-EnhancementPack/blob/234e1791c7a8bcbf1163b8c28b5de212806d82bf/Source/Overlays/TreeGrowthOverlay.cs#L65) and [Overlays/PlantHarvestOverlay.cs](https://github.com/alextd/RimWorld-EnhancementPack/blob/234e1791c7a8bcbf1163b8c28b5de212806d82bf/Source/Overlays/PlantHarvestOverlay.cs#L67) respectively.
These two functions, as far as I can tell, get called every tick, even when the respective overlays are closed.

I understand that there are checks in place to prevent the patches from resulting in further action beyond once every half minute or so. Would it still be possible to move these Patches out of `Verse.TickList` and find a way to reduce their impact while the overlays are closed?

Afaik Harmony patches still cost performance, as Harmony wraps the entire function in a list of separate function calls. Doing so for a function that gets called every single tick is decently costly.
We only gots 2.8ms, time is precious :)

**Comment by alextd** [comment]
I mean no a few function calls per frame is insignificant
